url: https://creatingsapien.github.io/Websiteholding/
baseurl: ""

# Site settings
title: Berkeley Data Science Group
email: team@bds.group
description: "We build your data science solutions!" 

# Team names, titles and social links
people:
- name: Denis Vrdoljak MIDS
  pic: 1
  position: Co-founder and CEO 
  social: 
    - title: Linkedin
      url: https://www.linkedin.com/in/mattstevenson2/


- name: Gunnar Kleemann MIDS PhD
  pic: 2
  position: Co-founder and Principal Data Scientist
  social:
    - title: twitter
      url: https://twitter.com/GunnarKleemann
    - title: Linkedin
      url: https://www.linkedin.com/in/gunnarkleemann/
    - title: Research site
      url: http://gunnarkleemann.net
   

- name: Matt Stevenson MIDS
  pic: 3
  position: Senior Data Scientist
  social:
    - title: Linkedin
      url: https://www.linkedin.com/in/mattstevenson2/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

  - title: Linkedin
    url: https://www.linkedin.com/company/berkeley-data-science-group
  - title: Facebook
    url: https://www.facebook.com/BerkeleyDataScienceGroup/
  - title: Github
    url: https://github.com/BerkeleyDataScienceGroup

# Postal address (add as many lines as necessary)
address:
  - line: Austin Texas

# Build settings
markdown: kramdown
permalink: pretty
